name: Deploy Lambda Listings Updater (Docker)

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'
      - '.github/workflows/deploy_lambda_update.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image
        env:
          ECR_REPO_NAME: rental-listings-updater
          IMAGE_TAG: latest
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REGION=us-east-1
          REPO_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO_NAME"

          # Create ECR repo if it doesn't exist
          aws ecr describe-repositories --repository-names "$ECR_REPO_NAME" || \
            aws ecr create-repository --repository-name "$ECR_REPO_NAME"

          # Build and push Docker image
          docker build -t $REPO_URI:$IMAGE_TAG ./lambda
          docker push $REPO_URI:$IMAGE_TAG

      - name: Update existing Lambda with new container image
        env:
          FUNCTION_NAME: rental-listings-updater-docker
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REGION=us-east-1
          IMAGE_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/rental-listings-updater:latest"

          # Update the existing Lambda function with new container image
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --image-uri "$IMAGE_URI"

          # Wait until Lambda update is complete
          aws lambda wait function-updated --function-name "$FUNCTION_NAME"