name: Deploy Lambda Listings Updater (Docker)

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'
      - '.github/workflows/deploy_lambda_update.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image to ECR
        env:
          ECR_REPO_NAME: rental-listings-updater
          IMAGE_TAG: latest
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REGION=us-east-1
          REPO_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO_NAME"

          # Create ECR repo if it doesn't exist
          aws ecr describe-repositories --repository-names "$ECR_REPO_NAME" || \
            aws ecr create-repository --repository-name "$ECR_REPO_NAME"

          # Build Docker image
          docker build -t $REPO_URI:$IMAGE_TAG ./lambda

          # Push image to ECR
          docker push $REPO_URI:$IMAGE_TAG

      - name: Deploy Lambda using container image
        env:
          FUNCTION_NAME: rental-listings-updater
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REGION=us-east-1
          IMAGE_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/rental-listings-updater:latest"

          # Check if function exists
          if aws lambda get-function --function-name "$FUNCTION_NAME"; then
            echo "Updating existing Lambda function with container image..."
            aws lambda update-function-code \
              --function-name "$FUNCTION_NAME" \
              --image-uri "$IMAGE_URI"
          else
            echo "Creating new Lambda function with container image..."
            aws lambda create-function \
              --function-name "$FUNCTION_NAME" \
              --package-type Image \
              --code ImageUri="$IMAGE_URI" \
              --role ${{ secrets.AWS_LAMBDA_EXECUTION_ROLE_ARN }}
          fi

          # Wait until Lambda is fully updated
          aws lambda wait function-updated --function-name "$FUNCTION_NAME"