name: Deploy Lambda Listings Updater

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/config.py'
      - 'lambda/db.py'
      - 'lambda/rental_listings_updater.py'
      - '.github/workflows/deploy_lambda_update.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # --- Layer 1: pandas + numpy ---
      - name: Package Layer 1 (Core)
        run: |
          rm -rf lambda_layer1
          mkdir -p lambda_layer1/python/lib/python3.13/site-packages
          pip install --target=lambda_layer1/python/lib/python3.13/site-packages pandas numpy
          cd lambda_layer1
          find . -name "__pycache__" -type d -exec rm -rf {} +
          zip -r ../lambda_layer1.zip .
          cd ..
          LAYER1_ARN=$(aws lambda publish-layer-version \
            --layer-name rental-listings-updater-core \
            --zip-file fileb://lambda_layer1.zip \
            --compatible-runtimes python3.13 \
            --query LayerVersionArn \
            --output text)
          echo "LAYER1_ARN=$LAYER1_ARN" >> $GITHUB_ENV

      # --- Layer 2: All other dependencies + HomeHarvest ---
      - name: Package Layer 2 (Aux + HomeHarvest)
        run: |
          rm -rf lambda_layer2
          mkdir -p lambda_layer2/python/lib/python3.13/site-packages
          pip install --target=lambda_layer2/python/lib/python3.13/site-packages \
            sqlalchemy psycopg2-binary geopy googlemaps \
            homeharvest tls-client requests tenacity \
            pydantic annotated-types typing-extensions typing-inspection pydantic-core
          cd lambda_layer2
          find . -name "__pycache__" -type d -exec rm -rf {} +
          find . -name "*.dist-info" -type d -exec rm -rf {} +
          zip -r ../lambda_layer2.zip .
          cd ..
          LAYER2_ARN=$(aws lambda publish-layer-version \
            --layer-name rental-listings-updater-aux \
            --zip-file fileb://lambda_layer2.zip \
            --compatible-runtimes python3.13 \
            --query LayerVersionArn \
            --output text)
          echo "LAYER2_ARN=$LAYER2_ARN" >> $GITHUB_ENV

      # --- Package Lambda function ---
      - name: Package Lambda function
        run: |
          rm -f lambda_function.zip
          mkdir -p lambda_package
          cp lambda/config.py lambda_package/
          cp lambda/rental_listings_updater.py lambda_package/
          cp lambda/db.py lambda_package/
          cd lambda_package
          zip -r ../lambda_function.zip . -x "*__pycache__*"

      # --- Deploy Lambda safely ---
      - name: Deploy Lambda function
        run: |
          FUNCTION_NAME="rental-listings-updater"
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://lambda_function.zip \
            --publish
          aws lambda wait function-updated --function-name "$FUNCTION_NAME"
          aws lambda update-function-configuration \
            --function-name "$FUNCTION_NAME" \
            --layers $LAYER1_ARN $LAYER2_ARN
          aws lambda wait function-updated --function-name "$FUNCTION_NAME"