name: Deploy Lambda Listings Updater

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/config.py'
      - 'lambda/db.py'
      - 'lambda/rental_listings_updater.py'
      - '.github/workflows/deploy_lambda_update.yml'

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt
          pip install googlemaps geopy sqlalchemy psycopg2-binary pandas

      # 4. Package Lambda code
      - name: Package Lambda
        run: |
          rm -f lambda_function.zip
          mkdir -p lambda_package

          # Copy your code
          cp -r lambda/config.py lambda_package/
          cp -r lambda/rental_listings_updater.py lambda_package/
          cp -r lambda/db.py lambda_package/

          # Install dependencies into the package folder
          pip install --target=lambda_package -r lambda/requirements.txt

          # Zip everything
          cd lambda_package
          zip -r ../lambda_function.zip . -x "*__pycache__*"

      # 5. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 6. Deploy Lambda code
      - name: Update Lambda function code
        run: |
          FUNCTION_NAME="rental-listings-updater"
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://lambda_function.zip