name: Deploy Lambda Listings Updater

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/config.py'
      - 'lambda/db.py'
      - 'lambda/rental_listings_updater.py'
      - '.github/workflows/deploy_lambda_update.yml'

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Package dependencies as Lambda layer
      - name: Package Lambda dependencies as layer
        run: |
          rm -rf lambda_layer
          mkdir -p lambda_layer/python
          pip install --target=lambda_layer/python -r lambda/requirements.txt
          zip -r lambda_layer.zip lambda_layer

      - name: Publish Lambda Layer
        id: publish_layer
        run: |
          LAYER_ARN=$(aws lambda publish-layer-version \
            --layer-name rental-listings-updater-dependencies \
            --zip-file fileb://lambda_layer.zip \
            --compatible-runtimes python3.13 \
            --query LayerVersionArn \
            --output text)
          echo "LAYER_ARN=$LAYER_ARN" >> $GITHUB_ENV

      # Package Lambda function code
      - name: Package Lambda function
        run: |
          rm -f lambda_function.zip
          mkdir -p lambda_package
          cp -r lambda/config.py lambda_package/
          cp -r lambda/rental_listings_updater.py lambda_package/
          cp -r lambda/db.py lambda_package/
          cd lambda_package
          zip -r ../lambda_function.zip . -x "*__pycache__*"

      # Update Lambda code and attach layer
      - name: Deploy Lambda
        run: |
          FUNCTION_NAME="rental-listings-updater"
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://lambda_function.zip

          aws lambda update-function-configuration \
            --function-name "$FUNCTION_NAME" \
            --layers $LAYER_ARN